databases:
  - name: rezervem-db
    databaseName: rezervem
    user: rezervem

services:
  - type: web
    name: rezervem
    runtime: python
    buildCommand: ./build.sh
    startCommand: uvicorn online_reservation.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rezervem-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
